### ISSUE TITLE
Sync over TCP

### ISSUE THREAD

**Issue by Ivshti** [mafintosh/multi-master-merge#7]
How to replicate over TCP?

A simple 
```javascript
	var c = net.connect(url.parse(argv.replicate).port);
	c.on("connect", function() { db.sync().pipe(c) });
```
Plus
```javascript
db.listenReplications = function() {
	var server = net.createServer(function(c) { 
		console.log("DB replication connection established from "+c.remoteAddress+":"+c.remotePort);
		c.pipe(db.sync()); 
	});
	server.listen(function() {
		console.log("DB replication server listening at "+server.address().port);
	});
};
```

Does not work - on a second look at scuttleup looks like it uses the "connect" event, which conflicts with TCP's own connect. Obviously some kind of serialization would be needed.

How would that be done?

Is it a good idea to sync over a raw network socket at all, considering a use case where the data consistency is not a top priority?

**Comment by mafintosh** [comment]
You need to setup a duplex pipe. It's as simple as

``` js
var c = net.connect(...)
c.pipe(db.sync()).pipe(c)
```

**Comment by mafintosh** [comment]
Yup! replicating over raw tcp is a great use-case.

**Comment by Ivshti** [comment]
Shouldn't that be
```javascript
var c = net.connect(...)
 var syncStream = db.getSyncStream(); syncStream.pipe(c.pipe(syncStream))
```
	var server = net.createServer(function(c) { 
		c.pipe(db.getSyncStream().pipe(c)); 
	});
```
?

Seems that I've missed the obvious though, thanks!

I'll post code & close when I figure it out

**Comment by Ivshti** [comment]
No, sorry, it's exactly how you wrote it, although I don't fully understand why yet.

``c.pipe(db.sync())`` would just return c, but piping all it's events to db.sync(), so then piping it again to c? Doesn't ``c.pipe(db.sync().pipe(c))`` make more sense?

**Comment by mafintosh** [comment]
`c.pipe(db.sync())` returns the stream returned from `db.sync()`. you need to pipe that back into `c` since `c` is a duplex stream

**Comment by Ivshti** [comment]
Makes sense. Thanks
